#!/bin/sh

# Check whether a given config is contained in AB_PROMETHEUS_OPTS
is_in_prometheus_opts() {
  local prop=$1
  if [ -n "${AB_JMX_EXPORTER_OPTS:-}" ] && [ "${AB_JMX_EXPORTER_OPTS}" != "${AB_JMX_EXPORTER_OPTS/${prop}/}" ]; then
     echo "yes"
  else
     echo "no"
  fi
}

get_prometheus_properties() {

  echo "port=${AB_JMX_EXPORTER_PORT:-9779}"
  echo "config=${AB_JMX_EXPORTER_CONFIG:-/opt/prometheus/prometheus-config.yml}"

  if [ -n "${AB_PROMETHEUS_OPTS:-}" ]; then
     echo "${AB_PROMETHEUS_OPTS}" | tr "," "\n"
  fi

}

write_prometheus_properties() {
  local prometheus_property_file="$1"

  touch "${prometheus_property_file}"
  chmod 660 "${prometheus_property_file}"
  cat > "${prometheus_property_file}" <<EOF
$(get_prometheus_properties)
EOF

}

if [ -z "${AB_PROMETHEUS_PORT:-}" ]; then
   AB_PROMETHEUS_PORT="9779"
   export AB_PROMETHEUS_PORT
fi

if [ -z "${AB_JMX_EXPORTER_CONFIG:-}" ]; then
    AB_JMX_EXPORTER_CONFIG="/opt/prometheus/prometheus-config.yml"
    export AB_PROMETHEUS_CONFIG
fi

if [ -z "${AB_PROMETHEUS_OFF:-}" ]; then
  write_prometheus_properties "/opt/prometheus/etc/prometheus.properties"

  if [ -z "${AB_JMX_EXPORTER_OPTS:-}" ]; then
    if [ -z "${AB_PROMETHEUS_HOST:-}" ]; then
      echo "-javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=${AB_PROMETHEUS_PORT}:${AB_JMX_EXPORTER_CONFIG}"
    else
      echo "-javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=${AB_PROMETHEUS_HOST}:${AB_PROMETHEUS_PORT}:${AB_JMX_EXPORTER_CONFIG}"
    fi
  else
    echo "-javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=${AB_JMX_EXPORTER_OPTS}"
  fi
fi
